import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import LeftBar from "./left-bar";
import RightBar from "./right-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div className="h-screen flex w-screen" >
            <LeftBar />
            <div className="flex-1">
              {children}
            </div>
            <RightBar />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
